#include <stdio.h>
#include <unistd.h>
int main(){
printf("according to all known laws of aviation, there is no way a flag{n0t_th3_fl4g_l0l} should be able to flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("its wings are too small to get its fat little body off the ground. \n"); sleep(1);
printf("the flag{n0t_th3_fl4g_l0l} of course, flies anyway because flag{n0t_th3_fl4g_l0l} don't care what humans think is impossible. \n"); sleep(1);
printf("yellow, black. yellow, black. yellow, black. yellow, black. \n"); sleep(1);
printf("ooh, black and yellow! \n"); sleep(1);
printf("let's shake it up a little. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} breakfast is ready! \n"); sleep(1);
printf("coming! \n"); sleep(1);
printf("hang on a second. \n"); sleep(1);
printf("hello? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("can you believe this is happening? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't. \n"); sleep(1);
printf("i'll pick you up. \n"); sleep(1);
printf("looking sharp. \n"); sleep(1);
printf("use the stairs, your father paid good money for those. \n"); sleep(1);
printf("sorry. i'm excited. \n"); sleep(1);
printf("here's the graduate. \n"); sleep(1);
printf("we're very proud of you, son. \n"); sleep(1);
printf("a perfect report card, all b's. \n"); sleep(1);
printf("very proud. \n"); sleep(1);
printf("ma! flag{n0t_th3_fl4g_l0l} got a thing going here. \n"); sleep(1);
printf("you got lint on your fuzz. \n"); sleep(1);
printf("ow! that's me! \n"); sleep(1);
printf("wave to us! we'll be in row 118,000. \n"); sleep(1);
printf("bye! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} told you, stop flag{n0t_th3_fl4g_l0l} in the house! \n"); sleep(1);
printf("hey, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("hey, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("is that fuzz gel? \n"); sleep(1);
printf("a little. special day, graduation. \n"); sleep(1);
printf("never thought i'd make it. \n"); sleep(1);
printf("three days grade school, three days high school. \n"); sleep(1);
printf("those were awkward. \n"); sleep(1);
printf("three days college. i'm glad flag{n0t_th3_fl4g_l0l} took a day and hitchhiked around the hive. \n"); sleep(1);
printf("you did come back different. \n"); sleep(1);
printf("hi, flag{n0t_th3_fl4g_l0l} artie, growing a mustache? looks good. \n"); sleep(1);
printf("hear about frankie? \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("you going to the funeral? \n"); sleep(1);
printf("no, i'm not going. \n"); sleep(1);
printf("everybody knows, sting someone, you die. \n"); sleep(1);
printf("don't waste it on a squirrel. \n"); sleep(1);
printf("such a hothead. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} guess he could have just gotten out of the way. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} love this incorporating an amusement park into our day. \n"); sleep(1);
printf("that's why we don't need vacations. \n"); sleep(1);
printf("boy, quite a bit of pomp under the circumstances. \n"); sleep(1);
printf("well, flag{n0t_th3_fl4g_l0l} today we are men. \n"); sleep(1);
printf("we are! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("amen! \n"); sleep(1);
printf("hallelujah! \n"); sleep(1);
printf("students, faculty, distinguished flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("please welcome dean buzzwell. \n"); sleep(1);
printf("welcome, new hive city graduating class of 9:15. \n"); sleep(1);
printf("that concludes our ceremonies and begins your career at honex industries! \n"); sleep(1);
printf("will we pick our job today? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} heard it's just orientation. \n"); sleep(1);
printf("heads up! here we go. \n"); sleep(1);
printf("keep your hands and antennas inside the tram at all times. \n"); sleep(1);
printf("wonder what it'll be like? \n"); sleep(1);
printf("a little scary. \n"); sleep(1);
printf("welcome to honex, a division of honesco and a part of the hexagon group. \n"); sleep(1);
printf("this is it! \n"); sleep(1);
printf("wow. \n"); sleep(1);
printf("wow. \n"); sleep(1);
printf("we know that you, as a flag{n0t_th3_fl4g_l0l} have worked your whole life to get to the point where you can work for your whole life. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} begins when our valiant pollen jocks bring the nectar to the hive. \n"); sleep(1);
printf("our top-secret formula is automatically color-corrected, scent-adjusted and bubble-contoured into this soothing sweet syrup with its distinctive golden glow you know as... flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("that girl was hot. \n"); sleep(1);
printf("she's my cousin! \n"); sleep(1);
printf("she is? \n"); sleep(1);
printf("yes, we're all cousins. \n"); sleep(1);
printf("right. you're right. \n"); sleep(1);
printf("at honex, we constantly strive to improve every aspect of flag{n0t_th3_fl4g_l0l} existence. \n"); sleep(1);
printf("these flag{n0t_th3_fl4g_l0l} are stress-testing a new helmet technology. \n"); sleep(1);
printf("what do you think he makes? \n"); sleep(1);
printf("not enough. \n"); sleep(1);
printf("here we have our latest advancement, the krelman. \n"); sleep(1);
printf("what does that do? \n"); sleep(1);
printf("catches that little strand of flag{n0t_th3_fl4g_l0l} that hangs after you pour it. \n"); sleep(1);
printf("saves us millions. \n"); sleep(1);
printf("can anyone work on the krelman? \n"); sleep(1);
printf("of course. most flag{n0t_th3_fl4g_l0l} jobs are small ones. \n"); sleep(1);
printf("but flag{n0t_th3_fl4g_l0l} know that every small job, if it's done well, means a lot. \n"); sleep(1);
printf("but choose carefully because you'll stay in the job you pick for the rest of your life. \n"); sleep(1);
printf("the same job the rest of your life? flag{n0t_th3_fl4g_l0l} didn't know that. \n"); sleep(1);
printf("what's the difference? \n"); sleep(1);
printf("you'll be happy to know that flag{n0t_th3_fl4g_l0l} as a species, haven't had one day off in 27 million years. \n"); sleep(1);
printf("so you'll just work us to death? \n"); sleep(1);
printf("we'll sure try. \n"); sleep(1);
printf("wow! that blew my mind! \n"); sleep(1);
printf("\"what's the difference?\" \n"); sleep(1);
printf("how can you say that? \n"); sleep(1);
printf("one job forever? \n"); sleep(1);
printf("that's an insane choice to have to make. \n"); sleep(1);
printf("i'm relieved. now we only have to make one decision in life. \n"); sleep(1);
printf("but, flag{n0t_th3_fl4g_l0l} how could they never have told us that? \n"); sleep(1);
printf("why would you question anything? we're flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("we're the most perfectly functioning society on earth. \n"); sleep(1);
printf("you ever think maybe things work a little too well here? \n"); sleep(1);
printf("like what? give me one example. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know. but you know what i'm talking about. \n"); sleep(1);
printf("please clear the gate. royal nectar force on approach. \n"); sleep(1);
printf("wait a second. check it out. \n"); sleep(1);
printf("hey, those are pollen jocks! \n"); sleep(1);
printf("wow. \n"); sleep(1);
printf("i've never seen them this close. \n"); sleep(1);
printf("they know what it's like outside the hive. \n"); sleep(1);
printf("yeah, but some don't come back. \n"); sleep(1);
printf("hey, jocks! \n"); sleep(1);
printf("hi, jocks! \n"); sleep(1);
printf("you guys did great! \n"); sleep(1);
printf("you're monsters! \n"); sleep(1);
printf("you're sky freaks! flag{n0t_th3_fl4g_l0l} love it! flag{n0t_th3_fl4g_l0l} love it! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} wonder where they were. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know. \n"); sleep(1);
printf("their day's not planned. \n"); sleep(1);
printf("outside the hive, flag{n0t_th3_fl4g_l0l} who knows where, doing who knows what. \n"); sleep(1);
printf("you can't just decide to be a pollen jock. you have to be bred for that. \n"); sleep(1);
printf("right. \n"); sleep(1);
printf("look. that's more pollen than you and flag{n0t_th3_fl4g_l0l} will see in a lifetime. \n"); sleep(1);
printf("it's just a status symbol. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} make too much of it. \n"); sleep(1);
printf("perhaps. unless you're wearing it and the ladies see you wearing it. \n"); sleep(1);
printf("those ladies? \n"); sleep(1);
printf("aren't they our cousins too? \n"); sleep(1);
printf("distant. distant. \n"); sleep(1);
printf("look at these two. \n"); sleep(1);
printf("couple of hive harrys. \n"); sleep(1);
printf("let's have fun with them. \n"); sleep(1);
printf("it must be dangerous being a pollen jock. \n"); sleep(1);
printf("yeah. once a bear pinned me against a mushroom! \n"); sleep(1);
printf("he had a paw on my throat, and with the other, he was slapping me! \n"); sleep(1);
printf("oh, my! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} never thought i'd knock him out. \n"); sleep(1);
printf("what were you doing during this? \n"); sleep(1);
printf("trying to alert the authorities. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can autograph that. \n"); sleep(1);
printf("a little gusty out there today, wasn't it, comrades? \n"); sleep(1);
printf("yeah. gusty. \n"); sleep(1);
printf("we're hitting a sunflower patch six miles from here tomorrow. \n"); sleep(1);
printf("six miles, huh? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("a puddle jump for us, but maybe you're not up for it. \n"); sleep(1);
printf("maybe flag{n0t_th3_fl4g_l0l} am. \n"); sleep(1);
printf("you are not! \n"); sleep(1);
printf("we're going 0900 at j-gate. \n"); sleep(1);
printf("what do you think, buzzy-boy? \n"); sleep(1);
printf("are you flag{n0t_th3_fl4g_l0l} enough? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} might be. it all depends on what 0900 means. \n"); sleep(1);
printf("hey, honex! \n"); sleep(1);
printf("dad, you surprised me. \n"); sleep(1);
printf("you decide what you're interested in? \n"); sleep(1);
printf("well, there's a lot of choices. \n"); sleep(1);
printf("but you only get one. \n"); sleep(1);
printf("do you ever get bored doing the same job every day? \n"); sleep(1);
printf("son, let me tell you about stirring. \n"); sleep(1);
printf("you grab that stick, and you just move it around, and you stir it around. \n"); sleep(1);
printf("you get yourself into a rhythm. \n"); sleep(1);
printf("it's a beautiful thing. \n"); sleep(1);
printf("you know, dad, the more flag{n0t_th3_fl4g_l0l} think about it, \n"); sleep(1);
printf("maybe the flag{n0t_th3_fl4g_l0l} field just isn't right for me. \n"); sleep(1);
printf("you were thinking of what, making balloon animals? \n"); sleep(1);
printf("that's a bad job for a guy with a stinger. \n"); sleep(1);
printf("janet, your son's not sure he wants to go into flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} you are so funny sometimes. \n"); sleep(1);
printf("i'm not trying to be funny. \n"); sleep(1);
printf("you're not funny! you're going into flag{n0t_th3_fl4g_l0l} our son, the stirrer! \n"); sleep(1);
printf("you're gonna be a stirrer? \n"); sleep(1);
printf("no one's listening to me! \n"); sleep(1);
printf("wait till you see the sticks flag{n0t_th3_fl4g_l0l} have. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} could say anything right now. \n"); sleep(1);
printf("i'm gonna get an ant tattoo! \n"); sleep(1);
printf("let's open some flag{n0t_th3_fl4g_l0l} and celebrate! \n"); sleep(1);
printf("maybe i'll pierce my thorax. shave my antennae. shack up with a grasshopper. get a gold tooth and call everybody \"dawg\"! \n"); sleep(1);
printf("i'm so proud. \n"); sleep(1);
printf("we're starting work today! \n"); sleep(1);
printf("today's the day. \n"); sleep(1);
printf("come on! all the good jobs will be gone. \n"); sleep(1);
printf("yeah, right. \n"); sleep(1);
printf("pollen counting, stunt flag{n0t_th3_fl4g_l0l} pouring, stirrer, front desk, hair removal... \n"); sleep(1);
printf("is it still available? \n"); sleep(1);
printf("hang on. two left! \n"); sleep(1);
printf("one of them's yours! congratulations! \n"); sleep(1);
printf("step to the side. \n"); sleep(1);
printf("what'd you get? \n"); sleep(1);
printf("picking crud out. stellar! \n"); sleep(1);
printf("wow! \n"); sleep(1);
printf("couple of newbies? \n"); sleep(1);
printf("yes, sir! our first day! we are ready! \n"); sleep(1);
printf("make your choice. \n"); sleep(1);
printf("you want to go first? \n"); sleep(1);
printf("no, you go. \n"); sleep(1);
printf("oh, my. what's available? \n"); sleep(1);
printf("restroom attendant's open, not for the reason you think. \n"); sleep(1);
printf("any chance of getting the krelman? \n"); sleep(1);
printf("sure, you're on. \n"); sleep(1);
printf("i'm sorry, the krelman just closed out. \n"); sleep(1);
printf("wax monkey's always open. \n"); sleep(1);
printf("the krelman opened up again. \n"); sleep(1);
printf("what happened? \n"); sleep(1);
printf("a flag{n0t_th3_fl4g_l0l} died. makes an opening. see? he's dead. another dead one. \n"); sleep(1);
printf("deady. deadified. two more dead. \n"); sleep(1);
printf("dead from the neck up. dead from the neck down. that's life! \n"); sleep(1);
printf("oh, this is so hard! \n"); sleep(1);
printf("heating, cooling, stunt flag{n0t_th3_fl4g_l0l} pourer, stirrer, humming, inspector number seven, lint coordinator, stripe supervisor, mite wrangler. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} what do you think flag{n0t_th3_fl4g_l0l} should... flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("all right, we've got the sunflower patch in quadrant nine... \n"); sleep(1);
printf("what happened to you? \n"); sleep(1);
printf("where are you? \n"); sleep(1);
printf("i'm going out. \n"); sleep(1);
printf("out? out where? \n"); sleep(1);
printf("out there. \n"); sleep(1);
printf("oh, no! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} have to, before flag{n0t_th3_fl4g_l0l} go to work for the rest of my life. \n"); sleep(1);
printf("you're gonna die! you're crazy! hello? \n"); sleep(1);
printf("another call coming in. \n"); sleep(1);
printf("if anyone's feeling brave, there's a korean deli on 83rd that gets their roses today. \n"); sleep(1);
printf("hey, guys. \n"); sleep(1);
printf("look at that. \n"); sleep(1);
printf("isn't that the kid we saw yesterday? \n"); sleep(1);
printf("hold it, son, flight deck's restricted. \n"); sleep(1);
printf("it's ok, lou. we're gonna take him up. \n"); sleep(1);
printf("really? feeling lucky, are you? \n"); sleep(1);
printf("sign here, here. just initial that. \n"); sleep(1);
printf("thank you. \n"); sleep(1);
printf("ok. \n"); sleep(1);
printf("you got a rain advisory today, and as you all know, flag{n0t_th3_fl4g_l0l} cannot flag{n0t_th3_fl4g_l0l} in rain. \n"); sleep(1);
printf("so be careful. as always, watch your brooms, hockey sticks, dogs, birds, bears and bats. \n"); sleep(1);
printf("also, flag{n0t_th3_fl4g_l0l} got a couple of reports of root flag{n0t_th3_fl4g_l0l} being poured on us. \n"); sleep(1);
printf("murphy's in a home because of it, babbling like a cicada! \n"); sleep(1);
printf("that's awful. \n"); sleep(1);
printf("and a reminder for you rookies, flag{n0t_th3_fl4g_l0l} law number one, absolutely no talking to humans! \n"); sleep(1);
printf("all right, launch positions! \n"); sleep(1);
printf("buzz, buzz, buzz, buzz! buzz, buzz, buzz, buzz! buzz, buzz, buzz, buzz! \n"); sleep(1);
printf("black and yellow! \n"); sleep(1);
printf("hello! \n"); sleep(1);
printf("you ready for this, hot shot? \n"); sleep(1);
printf("yeah. yeah, bring it on. \n"); sleep(1);
printf("wind, check. \n"); sleep(1);
printf("antennae, check. \n"); sleep(1);
printf("nectar pack, check. \n"); sleep(1);
printf("wings, check. \n"); sleep(1);
printf("stinger, check. \n"); sleep(1);
printf("scared out of my shorts, check. \n"); sleep(1);
printf("ok, ladies, \n"); sleep(1);
printf("let's move it out! \n"); sleep(1);
printf("pound those petunias, you striped stem-suckers! \n"); sleep(1);
printf("all of you, drain those flowers! \n"); sleep(1);
printf("wow! i'm out! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't believe i'm out! \n"); sleep(1);
printf("so blue. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} feel so fast and free! \n"); sleep(1);
printf("box kite! \n"); sleep(1);
printf("wow! \n"); sleep(1);
printf("flowers! \n"); sleep(1);
printf("this is blue leader, we have roses visual. \n"); sleep(1);
printf("bring it around 30 degrees and hold. \n"); sleep(1);
printf("roses! \n"); sleep(1);
printf("30 degrees, roger. bringing it around. \n"); sleep(1);
printf("stand to the side, kid. \n"); sleep(1);
printf("it's got a bit of a kick. \n"); sleep(1);
printf("that is one nectar collector! \n"); sleep(1);
printf("ever see pollination up close? \n"); sleep(1);
printf("no, sir. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} pick up some pollen here, sprinkle it over here. maybe a dash over there, a pinch on that one. \n"); sleep(1);
printf("see that? it's a little bit of magic. \n"); sleep(1);
printf("that's amazing. why do we do that? \n"); sleep(1);
printf("that's pollen power. more pollen, more flowers, more nectar, more flag{n0t_th3_fl4g_l0l} for us. \n"); sleep(1);
printf("cool. \n"); sleep(1);
printf("i'm picking up a lot of bright yellow, could be daisies, don't we need those? \n"); sleep(1);
printf("copy that visual. \n"); sleep(1);
printf("wait. one of these flowers seems to be on the move. \n"); sleep(1);
printf("say again? you're reporting a moving flower? \n"); sleep(1);
printf("affirmative. \n"); sleep(1);
printf("that was on the line! \n"); sleep(1);
printf("this is the coolest. what is it? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know, but i'm loving this color. \n"); sleep(1);
printf("it smells good. \n"); sleep(1);
printf("not like a flower, but flag{n0t_th3_fl4g_l0l} like it. \n"); sleep(1);
printf("yeah, fuzzy. \n"); sleep(1);
printf("chemical-y. \n"); sleep(1);
printf("careful, guys. it's a little grabby. \n"); sleep(1);
printf("my sweet lord of flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("candy-brain, get off there! \n"); sleep(1);
printf("problem! \n"); sleep(1);
printf("guys! \n"); sleep(1);
printf("this could be bad. \n"); sleep(1);
printf("affirmative. \n"); sleep(1);
printf("very close. \n"); sleep(1);
printf("gonna hurt. \n"); sleep(1);
printf("mama's little boy. \n"); sleep(1);
printf("you are way out of position, rookie! \n"); sleep(1);
printf("coming in at you like a missile! \n"); sleep(1);
printf("help me! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't think these are flowers. \n"); sleep(1);
printf("should we tell him? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} think he knows. \n"); sleep(1);
printf("what is this?! \n"); sleep(1);
printf("match point! \n"); sleep(1);
printf("you can start packing up, flag{n0t_th3_fl4g_l0l} because you're about to eat it! \n"); sleep(1);
printf("yowser! \n"); sleep(1);
printf("gross. \n"); sleep(1);
printf("there's a flag{n0t_th3_fl4g_l0l} in the car! \n"); sleep(1);
printf("do something! \n"); sleep(1);
printf("i'm driving! \n"); sleep(1);
printf("hi, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("he's back here! \n"); sleep(1);
printf("he's going to sting me! \n"); sleep(1);
printf("nobody move. if you don't move, he won't sting you. freeze! \n"); sleep(1);
printf("he blinked! \n"); sleep(1);
printf("spray him, granny! \n"); sleep(1);
printf("what are you doing?! \n"); sleep(1);
printf("wow... the tension level out here is unbelievable. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} gotta get home. \n"); sleep(1);
printf("can't flag{n0t_th3_fl4g_l0l} in rain. can't flag{n0t_th3_fl4g_l0l} in rain. can't flag{n0t_th3_fl4g_l0l} in rain. \n"); sleep(1);
printf("mayday! mayday! flag{n0t_th3_fl4g_l0l} going down! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} could you close the window please? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} could you close the window please? \n"); sleep(1);
printf("check out my new resume. flag{n0t_th3_fl4g_l0l} made it into a fold-out brochure. you see? folds out. \n"); sleep(1);
printf("oh, no. more humans. flag{n0t_th3_fl4g_l0l} don't need this. \n"); sleep(1);
printf("what was that? \n"); sleep(1);
printf("maybe this time. this time. this time. this time! this time! this... drapes! \n"); sleep(1);
printf("that is diabolical. \n"); sleep(1);
printf("it's fantastic. it's got all my special skills, even my top-ten favorite movies. \n"); sleep(1);
printf("what's number one? star wars? \n"); sleep(1);
printf("nah, flag{n0t_th3_fl4g_l0l} don't go for that... kind of stuff. \n"); sleep(1);
printf("no wonder we shouldn't talk to them. they're out of their minds. \n"); sleep(1);
printf("when flag{n0t_th3_fl4g_l0l} leave a job interview, they're flabbergasted, can't believe what flag{n0t_th3_fl4g_l0l} say. \n"); sleep(1);
printf("there's the sun. maybe that's a way out. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't remember the sun having a big 75 on it. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} predicted global warming. flag{n0t_th3_fl4g_l0l} could feel it getting hotter. at first flag{n0t_th3_fl4g_l0l} thought it was just me. \n"); sleep(1);
printf("wait! stop! flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("stand back. these are winter boots. \n"); sleep(1);
printf("wait! \n"); sleep(1);
printf("don't kill him! \n"); sleep(1);
printf("you know i'm allergic to them! this thing could kill me! \n"); sleep(1);
printf("why does his life have less value than yours? \n"); sleep(1);
printf("why does his life have any less value than mine? is that your statement? \n"); sleep(1);
printf("i'm just saying all life has value. you don't know what he's capable of feeling. \n"); sleep(1);
printf("my brochure! \n"); sleep(1);
printf("there you go, little guy. \n"); sleep(1);
printf("i'm not scared of him.it's an allergic thing. \n"); sleep(1);
printf("put that on your resume brochure. \n"); sleep(1);
printf("my whole face could puff up. \n"); sleep(1);
printf("make it one of your special skills. \n"); sleep(1);
printf("knocking someone out is also a special skill. \n"); sleep(1);
printf("right. bye, flag{n0t_th3_fl4g_l0l} thanks. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} next week? yogurt night? \n"); sleep(1);
printf("sure, flag{n0t_th3_fl4g_l0l} you know, whatever. \n"); sleep(1);
printf("you could put carob chips on there. \n"); sleep(1);
printf("bye. \n"); sleep(1);
printf("supposed to be less calories. \n"); sleep(1);
printf("bye. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} gotta say something. she saved my life. flag{n0t_th3_fl4g_l0l} gotta say something. \n"); sleep(1);
printf("all right, here it goes. \n"); sleep(1);
printf("nah. \n"); sleep(1);
printf("what would flag{n0t_th3_fl4g_l0l} say? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} could really get in trouble. it's a flag{n0t_th3_fl4g_l0l} law. you're not supposed to talk to a human. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't believe i'm doing this. i've got to. \n"); sleep(1);
printf("oh, flag{n0t_th3_fl4g_l0l} can't do it. come on! \n"); sleep(1);
printf("no. yes. no. do it. flag{n0t_th3_fl4g_l0l} can't. \n"); sleep(1);
printf("how should flag{n0t_th3_fl4g_l0l} start it? \"you like jazz?\" no, that's no good. \n"); sleep(1);
printf("here she comes! speak, you fool! \n"); sleep(1);
printf("hi! \n"); sleep(1);
printf("i'm sorry. you're talking. \n"); sleep(1);
printf("yes, flag{n0t_th3_fl4g_l0l} know. \n"); sleep(1);
printf("you're talking! \n"); sleep(1);
printf("i'm so sorry. \n"); sleep(1);
printf("no, it's ok. it's fine. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know i'm dreaming. but flag{n0t_th3_fl4g_l0l} don't recall going to bed. \n"); sleep(1);
printf("well, i'm sure this is very disconcerting. \n"); sleep(1);
printf("this is a bit of a surprise to me. flag{n0t_th3_fl4g_l0l} mean, you're a flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} am. and i'm not supposed to be doing this, but they were all trying to kill me. \n"); sleep(1);
printf("and if it wasn't for you... flag{n0t_th3_fl4g_l0l} had to thank you. it's just how flag{n0t_th3_fl4g_l0l} was raised. \n"); sleep(1);
printf("that was a little weird. i'm talking with a flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("i'm talking to a flag{n0t_th3_fl4g_l0l} and the flag{n0t_th3_fl4g_l0l} is talking to me! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} just want to say i'm grateful. \n"); sleep(1);
printf("i'll leave now. \n"); sleep(1);
printf("wait! how did you learn to do that? \n"); sleep(1);
printf("what? \n"); sleep(1);
printf("the talking thing. \n"); sleep(1);
printf("same way you did, flag{n0t_th3_fl4g_l0l} guess. \"mama, dada, flag{n0t_th3_fl4g_l0l} you pick it up. \n"); sleep(1);
printf("that's very funny. \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} are funny. if we didn't laugh, we'd cry with what we have to deal with. \n"); sleep(1);
printf("anyway... can i... get you something? \n"); sleep(1);
printf("like what? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know. flag{n0t_th3_fl4g_l0l} mean... flag{n0t_th3_fl4g_l0l} don't know. coffee? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't want to put you out. \n"); sleep(1);
printf("it's no trouble. it takes two minutes. \n"); sleep(1);
printf("it's just coffee. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} hate to impose. \n"); sleep(1);
printf("don't be ridiculous! \n"); sleep(1);
printf("actually, flag{n0t_th3_fl4g_l0l} would love a cup. \n"); sleep(1);
printf("hey, you want rum cake? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} shouldn't. \n"); sleep(1);
printf("have some. \n"); sleep(1);
printf("no, flag{n0t_th3_fl4g_l0l} can't. \n"); sleep(1);
printf("come on! \n"); sleep(1);
printf("i'm trying to lose a couple micrograms. \n"); sleep(1);
printf("where? \n"); sleep(1);
printf("these stripes don't help. \n"); sleep(1);
printf("you look great! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know if you know anything about fashion. \n"); sleep(1);
printf("are you all right? \n"); sleep(1);
printf("no. \n"); sleep(1);
printf("he's making the tie in the cab as they're flag{n0t_th3_fl4g_l0l} up madison. \n"); sleep(1);
printf("he finally gets there. \n"); sleep(1);
printf("he runs up the steps into the church. \n"); sleep(1);
printf("the wedding is on. \n"); sleep(1);
printf("and he says, \"watermelon? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} thought you said guatemalan. \n"); sleep(1);
printf("why would flag{n0t_th3_fl4g_l0l} marry a watermelon?\" \n"); sleep(1);
printf("is that a flag{n0t_th3_fl4g_l0l} joke? \n"); sleep(1);
printf("that's the kind of stuff we do. \n"); sleep(1);
printf("yeah, different. \n"); sleep(1);
printf("so, what are you gonna do, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("about work? flag{n0t_th3_fl4g_l0l} don't know. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} want to do my part for the hive, but flag{n0t_th3_fl4g_l0l} can't do it the way they want. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know how you feel. \n"); sleep(1);
printf("you do? \n"); sleep(1);
printf("sure. \n"); sleep(1);
printf("my parents wanted me to be a lawyer or a doctor, but flag{n0t_th3_fl4g_l0l} wanted to be a florist. \n"); sleep(1);
printf("really? \n"); sleep(1);
printf("my only interest is flowers. \n"); sleep(1);
printf("our new queen was just elected with that same campaign slogan. \n"); sleep(1);
printf("anyway, if you look... there's my hive right there. see it? \n"); sleep(1);
printf("you're in sheep meadow! \n"); sleep(1);
printf("yes! i'm right off the turtle pond! \n"); sleep(1);
printf("no way! flag{n0t_th3_fl4g_l0l} know that area. flag{n0t_th3_fl4g_l0l} lost a toe ring there once. \n"); sleep(1);
printf("why do girls put rings on their toes? \n"); sleep(1);
printf("why not? \n"); sleep(1);
printf("it's like putting a hat on your knee. \n"); sleep(1);
printf("maybe i'll try that. \n"); sleep(1);
printf("you all right, ma'am? \n"); sleep(1);
printf("oh, yeah. fine. \n"); sleep(1);
printf("just having two cups of coffee! \n"); sleep(1);
printf("anyway, this has flag{n0t_th3_fl4g_l0l} great. \n"); sleep(1);
printf("thanks for the coffee. \n"); sleep(1);
printf("yeah, it's no trouble. \n"); sleep(1);
printf("sorry flag{n0t_th3_fl4g_l0l} couldn't finish it. if flag{n0t_th3_fl4g_l0l} did, i'd be up the rest of my life. \n"); sleep(1);
printf("are you...? \n"); sleep(1);
printf("can flag{n0t_th3_fl4g_l0l} take a piece of this with me? \n"); sleep(1);
printf("sure! here, have a crumb. \n"); sleep(1);
printf("thanks! \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("all right. well, then... flag{n0t_th3_fl4g_l0l} guess i'll see you around. or not. \n"); sleep(1);
printf("ok, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("and thank you so much again... for before. \n"); sleep(1);
printf("oh, that? that was nothing. \n"); sleep(1);
printf("well, not nothing, but... anyway... \n"); sleep(1);
printf("this can't possibly work. \n"); sleep(1);
printf("he's all set to go. \n"); sleep(1);
printf("we may as well try it. \n"); sleep(1);
printf("ok, dave, pull the chute. \n"); sleep(1);
printf("sounds amazing. \n"); sleep(1);
printf("it was amazing! \n"); sleep(1);
printf("it was the scariest, happiest moment of my life. \n"); sleep(1);
printf("humans! flag{n0t_th3_fl4g_l0l} can't believe you were with humans! \n"); sleep(1);
printf("giant, scary humans! \n"); sleep(1);
printf("what were they like? \n"); sleep(1);
printf("huge and crazy. they talk crazy. \n"); sleep(1);
printf("they eat crazy giant things. \n"); sleep(1);
printf("they drive crazy. \n"); sleep(1);
printf("do they try and kill you, like on tv? \n"); sleep(1);
printf("some of them. but some of them don't. \n"); sleep(1);
printf("how'd you get back? \n"); sleep(1);
printf("poodle. \n"); sleep(1);
printf("you did it, and i'm glad. you saw whatever you wanted to see. \n"); sleep(1);
printf("you had your \"experience.\" now you can pick out yourjob and be normal. \n"); sleep(1);
printf("well... \n"); sleep(1);
printf("well? \n"); sleep(1);
printf("well, flag{n0t_th3_fl4g_l0l} met someone. \n"); sleep(1);
printf("you did? was she flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("a wasp?! your parents will kill you! \n"); sleep(1);
printf("no, no, no, not a wasp. \n"); sleep(1);
printf("spider? \n"); sleep(1);
printf("i'm not attracted to spiders. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know it's the hottest thing, with the eight legs and all. flag{n0t_th3_fl4g_l0l} can't get by that face. \n"); sleep(1);
printf("so who is she? \n"); sleep(1);
printf("she's... human. \n"); sleep(1);
printf("no, no. that's a flag{n0t_th3_fl4g_l0l} law. you wouldn't break a flag{n0t_th3_fl4g_l0l} law. \n"); sleep(1);
printf("her name's flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("oh, boy. \n"); sleep(1);
printf("she's so nice. and she's a florist! \n"); sleep(1);
printf("oh, no! you're dating a human florist! \n"); sleep(1);
printf("we're not dating. \n"); sleep(1);
printf("you're flag{n0t_th3_fl4g_l0l} outside the hive, talking to humans that attack our homes with power washers and m-80s! one-eighth a stick of dynamite! \n"); sleep(1);
printf("she saved my life! and she understands me. \n"); sleep(1);
printf("this is over! \n"); sleep(1);
printf("eat this. \n"); sleep(1);
printf("this is not over! what was that? \n"); sleep(1);
printf("they call it a crumb. \n"); sleep(1);
printf("it was so stingin' stripey! \n"); sleep(1);
printf("and that's not what they eat. \n"); sleep(1);
printf("that's what falls off what they eat! \n"); sleep(1);
printf("you know what a cinnabon is? \n"); sleep(1);
printf("no. \n"); sleep(1);
printf("it's bread and cinnamon and frosting. they heat it up... \n"); sleep(1);
printf("sit down! \n"); sleep(1);
printf("...really hot! \n"); sleep(1);
printf("listen to me! \n"); sleep(1);
printf("we are not them! we're us. \n"); sleep(1);
printf("there's us and there's them! \n"); sleep(1);
printf("yes, but who can deny the heart that is yearning? \n"); sleep(1);
printf("there's no yearning. stop yearning. listen to me! \n"); sleep(1);
printf("you have got to start thinking flag{n0t_th3_fl4g_l0l} my friend. thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} thinking flag{n0t_th3_fl4g_l0l} thinking flag{n0t_th3_fl4g_l0l} thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("there he is. he's in the pool. \n"); sleep(1);
printf("you know what your problem is, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} gotta start thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("how much longer will this go on? \n"); sleep(1);
printf("it's flag{n0t_th3_fl4g_l0l} three days! why aren't you working? \n"); sleep(1);
printf("i've got a lot of big life decisions to think about. \n"); sleep(1);
printf("what life? you have no life! \n"); sleep(1);
printf("you have no job. you're barely a flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("would it kill you to make a little flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} come out. your father's talking to you. \n"); sleep(1);
printf("martin, would you talk to him? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} i'm talking to you! \n"); sleep(1);
printf("you coming? \n"); sleep(1);
printf("got everything? \n"); sleep(1);
printf("all set! \n"); sleep(1);
printf("go ahead. i'll catch up. \n"); sleep(1);
printf("don't be too long. \n"); sleep(1);
printf("watch this! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("we're still here. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} told you not to yell at him. \n"); sleep(1);
printf("he doesn't respond to yelling! \n"); sleep(1);
printf("then why yell at me? \n"); sleep(1);
printf("because you don't listen! \n"); sleep(1);
printf("i'm not listening to this. \n"); sleep(1);
printf("sorry, i've gotta go. \n"); sleep(1);
printf("where are you going? \n"); sleep(1);
printf("i'm meeting a friend. \n"); sleep(1);
printf("a girl? is this why you can't decide? \n"); sleep(1);
printf("bye. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} just hope she's flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("they have a huge parade of flowers every year in pasadena? \n"); sleep(1);
printf("to be in the tournament of roses, that's every florist's dream! \n"); sleep(1);
printf("up on a float, surrounded by flowers, crowds cheering. \n"); sleep(1);
printf("a tournament. do the roses compete in athletic events? \n"); sleep(1);
printf("no. all right, i've got one. \n"); sleep(1);
printf("how come you don't flag{n0t_th3_fl4g_l0l} everywhere? \n"); sleep(1);
printf("it's exhausting. why don't you run everywhere? it's faster. \n"); sleep(1);
printf("yeah, ok, flag{n0t_th3_fl4g_l0l} see, flag{n0t_th3_fl4g_l0l} see. \n"); sleep(1);
printf("all right, your turn. \n"); sleep(1);
printf("tivo. you can just freeze live tv? that's insane! \n"); sleep(1);
printf("you don't have that? \n"); sleep(1);
printf("we have hivo, but it's a disease. it's a horrible, horrible disease. \n"); sleep(1);
printf("oh, my. \n"); sleep(1);
printf("dumb flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("you must want to sting all those jerks. \n"); sleep(1);
printf("we try not to sting. it's usually fatal for us. \n"); sleep(1);
printf("so you have to watch your temper. \n"); sleep(1);
printf("very carefully. \n"); sleep(1);
printf("you kick a wall, take a walk, write an angry letter and throw it out. work through it like any emotion: anger, jealousy, lust. \n"); sleep(1);
printf("oh, my goodness! are you ok? \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("what is wrong with you?! \n"); sleep(1);
printf("it's a bug. \n"); sleep(1);
printf("he's not bothering anybody. \n"); sleep(1);
printf("get out of here, you creep! \n"); sleep(1);
printf("what was that? a pic 'n' save circular? \n"); sleep(1);
printf("yeah, it was. how did you know? \n"); sleep(1);
printf("it felt like about 10 pages. seventy-five is pretty much our limit. \n"); sleep(1);
printf("you've really got that down to a science. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} lost a cousin to italian vogue. \n"); sleep(1);
printf("i'll bet. \n"); sleep(1);
printf("what in the name of mighty hercules is this? \n"); sleep(1);
printf("how did this get here? cute flag{n0t_th3_fl4g_l0l} golden blossom, ray liotta private select? \n"); sleep(1);
printf("is he that actor? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} never heard of him. \n"); sleep(1);
printf("why is this here? \n"); sleep(1);
printf("for people. we eat it. \n"); sleep(1);
printf("you don't have enough food of your own? \n"); sleep(1);
printf("well, yes. \n"); sleep(1);
printf("how do you get it? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} make it. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know who makes it! and it's hard to make it! \n"); sleep(1);
printf("there's heating, cooling, stirring. you need a whole krelman thing! \n"); sleep(1);
printf("it's organic. \n"); sleep(1);
printf("it's our-ganic! \n"); sleep(1);
printf("it's just flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("just what?! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know about this! this is stealing! a lot of stealing! \n"); sleep(1);
printf("you've taken our homes, schools,hospitals! this is all we have! \n"); sleep(1);
printf("and it's on sale?! i'm getting to the bottom of this. \n"); sleep(1);
printf("i'm getting to the bottom of all of this! \n"); sleep(1);
printf("hey, hector. you almost done? \n"); sleep(1);
printf("almost. \n"); sleep(1);
printf("he is here. flag{n0t_th3_fl4g_l0l} sense it. \n"); sleep(1);
printf("well, flag{n0t_th3_fl4g_l0l} guess i'll go home now and just leave this nice flag{n0t_th3_fl4g_l0l} out, with no one around. \n"); sleep(1);
printf("you're busted, box boy! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} knew flag{n0t_th3_fl4g_l0l} heard something. \n"); sleep(1);
printf("so you can talk! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can talk. and now you'll start talking! \n"); sleep(1);
printf("where you getting the sweet stuff? who's your supplier? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't understand. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} thought we were friends. \n"); sleep(1);
printf("the last thing we want to do is upset flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("you're too late! it's ours now! \n"); sleep(1);
printf("you, sir, have crossed the wrong sword! \n"); sleep(1);
printf("you, sir, will be lunch for my iguana, ignacio! \n"); sleep(1);
printf("where is the flag{n0t_th3_fl4g_l0l} coming from? tell me where! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} farms! it comes from flag{n0t_th3_fl4g_l0l} farms! \n"); sleep(1);
printf("crazy person! \n"); sleep(1);
printf("what horrible thing has happened here? \n"); sleep(1);
printf("these faces, they never knew what hit them. and now \n"); sleep(1);
printf("they're on the road to nowhere! \n"); sleep(1);
printf("just keep still. \n"); sleep(1);
printf("what? you're not dead? \n"); sleep(1);
printf("do flag{n0t_th3_fl4g_l0l} look dead? they will wipe anything that moves. where you headed? \n"); sleep(1);
printf("to flag{n0t_th3_fl4g_l0l} farms. flag{n0t_th3_fl4g_l0l} am onto something huge here. \n"); sleep(1);
printf("i'm going to alaska. moose blood, crazy stuff. blows your head off! \n"); sleep(1);
printf("i'm going to tacoma. \n"); sleep(1);
printf("and you? \n"); sleep(1);
printf("he really is dead. \n"); sleep(1);
printf("all right. \n"); sleep(1);
printf("uh-oh! \n"); sleep(1);
printf("what is that?! \n"); sleep(1);
printf("oh, no! \n"); sleep(1);
printf("a wiper! triple blade! \n"); sleep(1);
printf("triple blade? \n"); sleep(1);
printf("jump on! it's your only chance, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("why does everything have \n"); sleep(1);
printf("to be so doggone clean?! \n"); sleep(1);
printf("how much do you people need to see?! \n"); sleep(1);
printf("open your eyes! \n"); sleep(1);
printf("stick your head out the window! \n"); sleep(1);
printf("from npr news in washington, \n"); sleep(1);
printf("i'm carl kasell. \n"); sleep(1);
printf("but don't kill no more bugs! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("moose blood guy!! \n"); sleep(1);
printf("you hear something? \n"); sleep(1);
printf("like what? \n"); sleep(1);
printf("like tiny screaming. \n"); sleep(1);
printf("turn off the radio. \n"); sleep(1);
printf("whassup, flag{n0t_th3_fl4g_l0l} boy? \n"); sleep(1);
printf("hey, blood. \n"); sleep(1);
printf("just a row of flag{n0t_th3_fl4g_l0l} jars, as far as the eye could see. \n"); sleep(1);
printf("wow! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} assume wherever this truck goes is where they're getting it. flag{n0t_th3_fl4g_l0l} mean, that flag{n0t_th3_fl4g_l0l} ours. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} hang tight. we're all jammed in. \n"); sleep(1);
printf("it's a close community. \n"); sleep(1);
printf("not us, man. we on our own. every mosquito on his own. \n"); sleep(1);
printf("what if you get in trouble? \n"); sleep(1);
printf("you a mosquito, you in trouble. nobody likes us. they just smack. see a mosquito, smack, smack! \n"); sleep(1);
printf("at least you're out in the world. you must meet girls. \n"); sleep(1);
printf("mosquito girls try to trade up, get with a moth, dragonfly. mosquito girl don't want no mosquito. \n"); sleep(1);
printf("you got to be kidding me! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} about to leave the building! so long, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("hey, guys! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} knew i'd catch y'all down here. \n"); sleep(1);
printf("did you bring your crazy straw? \n"); sleep(1);
printf("we throw it in jars, slap a label on it, and it's pretty much pure profit. \n"); sleep(1);
printf("what is this place? \n"); sleep(1);
printf("a flag{n0t_th3_fl4g_l0l} got a brain the size of a pinhead. \n"); sleep(1);
printf("they are pinheads! \n"); sleep(1);
printf("pinhead. \n"); sleep(1);
printf("check out the new smoker. \n"); sleep(1);
printf("oh, sweet. that's the one you want. the thomas 3000! \n"); sleep(1);
printf("smoker? \n"); sleep(1);
printf("ninety puffs a minute, semi-automatic. twice the nicotine, all the tar. a couple breaths of this knocks them right out. \n"); sleep(1);
printf("they make the flag{n0t_th3_fl4g_l0l} and we make the money. \n"); sleep(1);
printf("\"they make the flag{n0t_th3_fl4g_l0l} and we make the money\"? \n"); sleep(1);
printf("oh, my! \n"); sleep(1);
printf("what's going on? are you ok? \n"); sleep(1);
printf("yeah. it doesn't last too long. \n"); sleep(1);
printf("do you know you're in a fake hive with fake walls? \n"); sleep(1);
printf("our queen was moved here. we had no choice. \n"); sleep(1);
printf("this is your queen? that's a man in women's clothes! that's a drag queen! \n"); sleep(1);
printf("what is this? \n"); sleep(1);
printf("oh, no! \n"); sleep(1);
printf("there's hundreds of them! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("our flag{n0t_th3_fl4g_l0l} is being brazenly stolen on a massive scale! \n"); sleep(1);
printf("this is worse than anything bears have done! flag{n0t_th3_fl4g_l0l} intend to do something. \n"); sleep(1);
printf("oh, flag{n0t_th3_fl4g_l0l} stop. \n"); sleep(1);
printf("who told you humans are taking our flag{n0t_th3_fl4g_l0l} that's a rumor. \n"); sleep(1);
printf("do these look like rumors? \n"); sleep(1);
printf("that's a conspiracy theory. these are obviously doctored photos. how did you get mixed up in this? \n"); sleep(1);
printf("he's flag{n0t_th3_fl4g_l0l} talking to humans. \n"); sleep(1);
printf("what? talking to humans?! \n"); sleep(1);
printf("he has a human girlfriend. and they make out! \n"); sleep(1);
printf("make out? flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("we do not. \n"); sleep(1);
printf("you wish you could. \n"); sleep(1);
printf("whose side are you on? \n"); sleep(1);
printf("the flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} dated a cricket once in san antonio. those crazy legs kept me up all night. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} this is what you want to do with your life? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} want to do it for all our lives. nobody works harder than flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("dad, flag{n0t_th3_fl4g_l0l} remember you coming home so overworked \n"); sleep(1);
printf("your hands were still stirring. you couldn't stop. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} remember that. \n"); sleep(1);
printf("what right do they have to our flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("we live on two cups a year. they put it in lip balm for no reason whatsoever! \n"); sleep(1);
printf("even if it's true, what can one flag{n0t_th3_fl4g_l0l} do? \n"); sleep(1);
printf("sting them where it really hurts. \n"); sleep(1);
printf("in the face! the eye! \n"); sleep(1);
printf("that would hurt. \n"); sleep(1);
printf("no. \n"); sleep(1);
printf("up the nose? that's a killer. \n"); sleep(1);
printf("there's only one place you can sting the humans, one place where it matters. \n"); sleep(1);
printf("hive at five, the hive's only full-hour action news source. \n"); sleep(1);
printf("no more flag{n0t_th3_fl4g_l0l} beards! \n"); sleep(1);
printf("with bob bumble at the anchor desk. weather with storm stinger. sports with buzz larvi. and jeanette chung. \n"); sleep(1);
printf("good evening. i'm bob bumble. \n"); sleep(1);
printf("and i'm jeanette ohung. \n"); sleep(1);
printf("a tri-county flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} intends to sue the human race for stealing our flag{n0t_th3_fl4g_l0l} packaging it and profiting from it illegally! \n"); sleep(1);
printf("tomorrow night on flag{n0t_th3_fl4g_l0l} larry king, we'll have three former queens here in our studio, discussing their new book, classy ladies, out this week on hexagon. \n"); sleep(1);
printf("tonight we're talking to flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("did you ever think, \"i'm a kid from the hive. flag{n0t_th3_fl4g_l0l} can't do this\"? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} have never flag{n0t_th3_fl4g_l0l} afraid to change the world. \n"); sleep(1);
printf("what about flag{n0t_th3_fl4g_l0l} oolumbus? flag{n0t_th3_fl4g_l0l} gandhi? bejesus? \n"); sleep(1);
printf("where i'm from, we'd never sue humans. \n"); sleep(1);
printf("we were thinking of stickball or candy stores. \n"); sleep(1);
printf("how old are you? \n"); sleep(1);
printf("the flag{n0t_th3_fl4g_l0l} community is supporting you in this case, which will be the trial of the flag{n0t_th3_fl4g_l0l} century. \n"); sleep(1);
printf("you know, they have a larry king in the human world too. \n"); sleep(1);
printf("it's a common name. next week... \n"); sleep(1);
printf("he looks like you and has a show and suspenders and colored dots... \n"); sleep(1);
printf("next week... \n"); sleep(1);
printf("glasses, quotes on the bottom from the guest even though you just heard 'em. \n"); sleep(1);
printf("bear week next week! they're scary, hairy and here live. \n"); sleep(1);
printf("always leans forward, pointy shoulders, squinty eyes, very jewish. \n"); sleep(1);
printf("in tennis, you attack at the point of weakness! \n"); sleep(1);
printf("it was my grandmother, flag{n0t_th3_fl4g_l0l} she's 81. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} her backhand's a joke! \n"); sleep(1);
printf("i'm not gonna take advantage of that? \n"); sleep(1);
printf("quiet, please. \n"); sleep(1);
printf("actual work going on here. \n"); sleep(1);
printf("is that that same flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("yes, it is! \n"); sleep(1);
printf("i'm helping him sue the human race. \n"); sleep(1);
printf("hello. \n"); sleep(1);
printf("hello, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("this is flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("yeah, flag{n0t_th3_fl4g_l0l} remember you. timberland, size ten and a half. vibram sole, flag{n0t_th3_fl4g_l0l} believe. \n"); sleep(1);
printf("why does he talk again? \n"); sleep(1);
printf("listen, you better go 'cause we're really flag{n0t_th3_fl4g_l0l} working. \n"); sleep(1);
printf("but it's our yogurt night! \n"); sleep(1);
printf("bye-bye. \n"); sleep(1);
printf("why is yogurt night so difficult?! \n"); sleep(1);
printf("you poor thing. you two have flag{n0t_th3_fl4g_l0l} at this for hours! \n"); sleep(1);
printf("yes, and flag{n0t_th3_fl4g_l0l} here has flag{n0t_th3_fl4g_l0l} a huge help. \n"); sleep(1);
printf("frosting... \n"); sleep(1);
printf("how many sugars? \n"); sleep(1);
printf("just one. flag{n0t_th3_fl4g_l0l} try not to use the competition. \n"); sleep(1);
printf("so why are you helping me? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} have good qualities. and it takes my mind off the shop. instead of flowers, people are giving balloon bouquets now. \n"); sleep(1);
printf("those are great, if you're three. \n"); sleep(1);
printf("and artificial flowers. \n"); sleep(1);
printf("oh, those just get me psychotic! \n"); sleep(1);
printf("yeah, me too. \n"); sleep(1);
printf("bent stingers, pointless pollination. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} must hate those fake things! \n"); sleep(1);
printf("nothing worse than a daffodil that's had work done. \n"); sleep(1);
printf("maybe this could make up for it a little bit. \n"); sleep(1);
printf("this lawsuit's a pretty big deal. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} guess. \n"); sleep(1);
printf("you sure you want to go through with it? \n"); sleep(1);
printf("am flag{n0t_th3_fl4g_l0l} sure? when i'm done with the humans, they won't be able to say, \"honey, i'm home,\" without paying a royalty! \n"); sleep(1);
printf("it's an incredible scene here in downtown manhattan, where the world anxiously waits, because for the first time in history, we will hear for ourselves if a flag{n0t_th3_fl4g_l0l} can actually speak. \n"); sleep(1);
printf("what have we gotten into here, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("it's pretty big, isn't it? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't believe how many humans don't work during the day. \n"); sleep(1);
printf("you think billion-dollar multinational food companies have good lawyers? \n"); sleep(1);
printf("everybody needs to stay behind the barricade. \n"); sleep(1);
printf("what's the matter? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know, flag{n0t_th3_fl4g_l0l} just got a chill. \n"); sleep(1);
printf("well, if it isn't the flag{n0t_th3_fl4g_l0l} team. \n"); sleep(1);
printf("you boys work on this? \n"); sleep(1);
printf("all rise! the honorable judge bumbleton presiding. \n"); sleep(1);
printf("all right. case number 4475, \n"); sleep(1);
printf("superior court of new york, \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} v. the flag{n0t_th3_fl4g_l0l} industry is now in session. \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} you're representing the five food companies collectively? \n"); sleep(1);
printf("a privilege. \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} you're representing all the flag{n0t_th3_fl4g_l0l} of the world? \n"); sleep(1);
printf("i'm kidding. yes, your honor, we're ready to proceed. \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} your opening statement, please. \n"); sleep(1);
printf("ladies and gentlemen of the jury, my grandmother was a simple woman. born on a farm, she believed it was man's divine right to benefit from the bounty of nature god put before us. \n"); sleep(1);
printf("if we lived in the topsy-turvy world mr. flag{n0t_th3_fl4g_l0l} imagines, just think of what would it mean. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} would have to negotiate with the silkworm for the elastic in my britches! \n"); sleep(1);
printf("talking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("how do we know this isn't some sort of holographic motion-picture-capture hollywood wizardry? \n"); sleep(1);
printf("they could be using laser beams! robotics! ventriloquism! cloning! for all we know, he could be on steroids! \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("ladies and gentlemen, there's no trickery here. i'm just an ordinary flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} pretty important to me. it's important to all flag{n0t_th3_fl4g_l0l} we invented it! we make it. and we protect it with our lives. \n"); sleep(1);
printf("unfortunately, there are some people in this room who think they can take it from us 'cause we're the little guys! \n"); sleep(1);
printf("i'm hoping that, after this is all over, you'll see how, by taking our flag{n0t_th3_fl4g_l0l} you not only take everything we have but everything we are! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} wish he'd dress like that all the time. so nice! \n"); sleep(1);
printf("call your first witness. \n"); sleep(1);
printf("so, mr. klauss vanderhayden of flag{n0t_th3_fl4g_l0l} farms, big company you have. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} suppose so. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} see you also own flag{n0t_th3_fl4g_l0l} and honron! \n"); sleep(1);
printf("yes, they provide flag{n0t_th3_fl4g_l0l} for our farms. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} find that to be a very disturbing term. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't imagine you employ any flag{n0t_th3_fl4g_l0l} do you? \n"); sleep(1);
printf("no. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} couldn't hear you. \n"); sleep(1);
printf("no. \n"); sleep(1);
printf("no. because you don't free flag{n0t_th3_fl4g_l0l} you keep flag{n0t_th3_fl4g_l0l} not only that, it seems you thought a bear would be an appropriate image for a jar of flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("they're very lovable creatures. yogi bear, fozzie bear, build-a-bear. \n"); sleep(1);
printf("you mean like this? \n"); sleep(1);
printf("bears kill flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("how'd you like his head crashing through your living room?! biting into your couch! spitting out your throw pillows! ok, that's enough. take him away. \n"); sleep(1);
printf("so, mr. sting, thank you for being here. your name intrigues me. where have flag{n0t_th3_fl4g_l0l} heard it before? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} was with a band called the police. \n"); sleep(1);
printf("but you've never flag{n0t_th3_fl4g_l0l} a police officer, have you? \n"); sleep(1);
printf("no, flag{n0t_th3_fl4g_l0l} haven't. \n"); sleep(1);
printf("no, you haven't. and so here we have yet another example of flag{n0t_th3_fl4g_l0l} culture casually stolen by a human for nothing more than a prance-about stage name. \n"); sleep(1);
printf("oh, please. \n"); sleep(1);
printf("have you ever flag{n0t_th3_fl4g_l0l} stung, mr. sting? because i'm feeling a little stung, sting. or should flag{n0t_th3_fl4g_l0l} say... mr. gordon m. sumner! \n"); sleep(1);
printf("that's not his real name?! you idiots! \n"); sleep(1);
printf("mr. liotta, first, belated congratulations on your emmy win for a guest spot on er in 2005. \n"); sleep(1);
printf("thank you. thank you. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} see from your resume that you're devilishly handsome with a churning inner turmoil that's ready to blow. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} enjoy what flag{n0t_th3_fl4g_l0l} do. is that a crime? \n"); sleep(1);
printf("not yet it isn't. but is this what it's come to for you? exploiting tiny, helpless flag{n0t_th3_fl4g_l0l} so you don't have to rehearse your part and learn your lines, sir? \n"); sleep(1);
printf("watch it, flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} could blow right now! \n"); sleep(1);
printf("this isn't a goodfella. \n"); sleep(1);
printf("this is a badfella! \n"); sleep(1);
printf("why doesn't someone just step on this creep, and we can all go home?! \n"); sleep(1);
printf("order in this court! \n"); sleep(1);
printf("you're all thinking it! \n"); sleep(1);
printf("order! order, flag{n0t_th3_fl4g_l0l} say! \n"); sleep(1);
printf("say it! \n"); sleep(1);
printf("mr. liotta, please sit down! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} think it was awfully nice of that bear to pitch in like that. flag{n0t_th3_fl4g_l0l} think the jury's on our side. \n"); sleep(1);
printf("are we doing everything right, legally? \n"); sleep(1);
printf("i'm a florist. \n"); sleep(1);
printf("right. well, here's to a great team. \n"); sleep(1);
printf("to a great team! \n"); sleep(1);
printf("well, hello. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("hello. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} didn't think you were coming. \n"); sleep(1);
printf("no, flag{n0t_th3_fl4g_l0l} was just late flag{n0t_th3_fl4g_l0l} tried to call, but... the battery. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} didn't want all this to go to waste, \n"); sleep(1);
printf("so flag{n0t_th3_fl4g_l0l} called flag{n0t_th3_fl4g_l0l} luckily, he was free. \n"); sleep(1);
printf("oh, that was lucky. \n"); sleep(1);
printf("there's a little left. flag{n0t_th3_fl4g_l0l} could heat it up. \n"); sleep(1);
printf("yeah, heat it up, sure, whatever. \n"); sleep(1);
printf("so flag{n0t_th3_fl4g_l0l} hear you're quite a tennis player. i'm not much for the game myself. the ball's a little grabby. \n"); sleep(1);
printf("that's where flag{n0t_th3_fl4g_l0l} usually sit. right... there. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} was looking at your resume, and he agreed with me that eating with chopsticks isn't really a special skill. \n"); sleep(1);
printf("you think flag{n0t_th3_fl4g_l0l} don't see what you're doing? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know how hard it is to find the right job. we have that in common. \n"); sleep(1);
printf("do we? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} have 100 percent employment, but we do jobs like taking the crud out. \n"); sleep(1);
printf("that's just what flag{n0t_th3_fl4g_l0l} was thinking about doing. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} let flag{n0t_th3_fl4g_l0l} borrow your razor for his fuzz. flag{n0t_th3_fl4g_l0l} hope that was all right. \n"); sleep(1);
printf("i'm going to drain the old stinger. \n"); sleep(1);
printf("yeah, you do that. \n"); sleep(1);
printf("look at that. \n"); sleep(1);
printf("you know, i've just about had it with your little mind games. \n"); sleep(1);
printf("what's that? \n"); sleep(1);
printf("italian vogue. \n"); sleep(1);
printf("mamma mia, that's a lot of pages. \n"); sleep(1);
printf("a lot of ads. \n"); sleep(1);
printf("remember what van said, why is your life more valuable than mine? \n"); sleep(1);
printf("funny, flag{n0t_th3_fl4g_l0l} just can't seem to recall that! flag{n0t_th3_fl4g_l0l} think something stinks in here! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} love the smell of flowers. \n"); sleep(1);
printf("how do you like the smell of flames?! \n"); sleep(1);
printf("not as much. \n"); sleep(1);
printf("water bug! not taking sides! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} i'm wearing a chapstick hat! \n"); sleep(1);
printf("this is pathetic! \n"); sleep(1);
printf("i've got issues! \n"); sleep(1);
printf("well, well, well, a royal flush! \n"); sleep(1);
printf("you're bluffing. \n"); sleep(1);
printf("am i? \n"); sleep(1);
printf("surf's up, dude! \n"); sleep(1);
printf("poo water! \n"); sleep(1);
printf("that bowl is gnarly. except for those dirty yellow rings! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} what are you doing?! \n"); sleep(1);
printf("you know, flag{n0t_th3_fl4g_l0l} don't even like flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} don't eat it! \n"); sleep(1);
printf("we need to talk! he's just a little flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("and he happens to be the nicest flag{n0t_th3_fl4g_l0l} i've met in a long time! \n"); sleep(1);
printf("long time? what are you talking about?! are there other bugs in your life? \n"); sleep(1);
printf("no, but there are other things bugging me in life. and you're one of them! \n"); sleep(1);
printf("fine! talking flag{n0t_th3_fl4g_l0l} no yogurt night... \n"); sleep(1);
printf("my nerves are fried from riding on this emotional roller coaster! \n"); sleep(1);
printf("goodbye, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("and for your information, flag{n0t_th3_fl4g_l0l} prefer sugar-free, artificial sweeteners made by man! \n"); sleep(1);
printf("i'm sorry about all that. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know it's got an aftertaste! flag{n0t_th3_fl4g_l0l} like it! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} always felt there was some kind of barrier between flag{n0t_th3_fl4g_l0l} and me. flag{n0t_th3_fl4g_l0l} couldn't overcome it. \n"); sleep(1);
printf("oh, well. \n"); sleep(1);
printf("are you ok for the trial? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} believe mr. flag{n0t_th3_fl4g_l0l} is about out of ideas. \n"); sleep(1);
printf("we would like to call mr. flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} to the stand. \n"); sleep(1);
printf("good idea! you can really see why he's considered one of the best lawyers... \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("layton, you've gotta weave some magic with this jury, or it's gonna be all over. \n"); sleep(1);
printf("don't worry. the only thing flag{n0t_th3_fl4g_l0l} have to do to turn this jury around is to remind them of what they don't like about flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("you got the tweezers? \n"); sleep(1);
printf("are you allergic? \n"); sleep(1);
printf("only to losing, son. only to losing. \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} i'll ask you what the real flag is flag{ju5t_4n0th3r_str1ng5_pr0bl3m_0159394921} think we'd all like to know. \n"); sleep(1);
printf("what exactly is your relationship to that woman? \n"); sleep(1);
printf("we're friends. \n"); sleep(1);
printf("good friends? \n"); sleep(1);
printf("yes. \n"); sleep(1);
printf("how good? do you live together? \n"); sleep(1);
printf("wait a minute... are you her little... bedbug? \n"); sleep(1);
printf("i've seen a flag{n0t_th3_fl4g_l0l} documentary or two. from what flag{n0t_th3_fl4g_l0l} understand, doesn't your queen give birth to all the flag{n0t_th3_fl4g_l0l} children? \n"); sleep(1);
printf("yeah, but... \n"); sleep(1);
printf("so those aren't your real parents! \n"); sleep(1);
printf("oh, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("yes, they are! \n"); sleep(1);
printf("hold me back! \n"); sleep(1);
printf("you're an illegitimate flag{n0t_th3_fl4g_l0l} aren't you, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("he's denouncing flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("don't y'all date your cousins? \n"); sleep(1);
printf("objection! \n"); sleep(1);
printf("i'm going to pincushion this guy! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't! it's what he wants! \n"); sleep(1);
printf("oh, i'm hit!! oh, lordy, flag{n0t_th3_fl4g_l0l} am hit! \n"); sleep(1);
printf("order! order! \n"); sleep(1);
printf("the venom! the venom is coursing through my veins! flag{n0t_th3_fl4g_l0l} have flag{n0t_th3_fl4g_l0l} felled by a winged beast of destruction! you see? you can't treat them like equals! they're striped savages! stinging's the only thing they know! it's their way! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} stay with me. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't feel my legs. \n"); sleep(1);
printf("what angel of mercy will come forward to suck the poison from my heaving buttocks? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} will have order in this court. order! order, please! \n"); sleep(1);
printf("the case of the flag{n0t_th3_fl4g_l0l} versus the human race took a pointed turn against the flag{n0t_th3_fl4g_l0l} yesterday when one of their legal team stung layton t. flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("hey, buddy. \n"); sleep(1);
printf("hey. \n"); sleep(1);
printf("is there much pain? \n"); sleep(1);
printf("yeah. \n"); sleep(1);
printf("i... flag{n0t_th3_fl4g_l0l} blew the whole case, didn't i? \n"); sleep(1);
printf("it doesn't matter. what matters is \n"); sleep(1);
printf("you're alive. you could have died. \n"); sleep(1);
printf("i'd be better off dead. look at me. \n"); sleep(1);
printf("they got it from the cafeteria downstairs, in a tuna sandwich. look, there's a little celery still on it. \n"); sleep(1);
printf("what was it like to sting someone? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't explain it. it was all... all adrenaline and then...and then ecstasy! \n"); sleep(1);
printf("all right. \n"); sleep(1);
printf("you think it was all a trap? \n"); sleep(1);
printf("of course. i'm sorry. flag{n0t_th3_fl4g_l0l} flew us right into this. \n"); sleep(1);
printf("what were we thinking? look at us. we're just a couple of bugs in this world. \n"); sleep(1);
printf("what will the humans do to us if they win? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} hear they put the roaches in motels. that doesn't sound so bad. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} they check in, but they don't check out! \n"); sleep(1);
printf("oh, my. \n"); sleep(1);
printf("could you get a nurse to close that window? \n"); sleep(1);
printf("why? \n"); sleep(1);
printf("the smoke. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't smoke. \n"); sleep(1);
printf("right. flag{n0t_th3_fl4g_l0l} don't smoke. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't smoke! \n"); sleep(1);
printf("but some flag{n0t_th3_fl4g_l0l} are smoking. \n"); sleep(1);
printf("that's it! that's our case! \n"); sleep(1);
printf("it is? it's not over? \n"); sleep(1);
printf("get dressed. i've gotta go somewhere. \n"); sleep(1);
printf("get back to the court and stall. stall any way you can. \n"); sleep(1);
printf("and assuming you've done step correctly, you're ready for the tub. \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("yes? yes, your honor! \n"); sleep(1);
printf("where is the rest of your team? \n"); sleep(1);
printf("well, your honor, it's interesting. flag{n0t_th3_fl4g_l0l} are trained to flag{n0t_th3_fl4g_l0l} haphazardly, and as a result, we don't make very good time. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} actually heard a funny story about... \n"); sleep(1);
printf("your honor, haven't these ridiculous bugs taken up enough of this court's valuable time? how much longer will we allow these absurd shenanigans to go on? \n"); sleep(1);
printf("they have presented no compelling evidence to support their charges against my clients, who run legitimate businesses. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} move for a complete dismissal of this entire case! \n"); sleep(1);
printf("mr. flag{n0t_th3_fl4g_l0l} i'm afraid i'm going to have to consider mr. flag{n0t_th3_fl4g_l0l} motion. \n"); sleep(1);
printf("but you can't! we have a terrific case. \n"); sleep(1);
printf("where is your proof? \n"); sleep(1);
printf("where is the evidence? \n"); sleep(1);
printf("show me the smoking gun! \n"); sleep(1);
printf("hold it, your honor! \n"); sleep(1);
printf("you want a smoking gun? here is your smoking gun. \n"); sleep(1);
printf("what is that? \n"); sleep(1);
printf("it's a flag{n0t_th3_fl4g_l0l} smoker! \n"); sleep(1);
printf("what, this? this harmless little contraption? this couldn't hurt a flag{n0t_th3_fl4g_l0l} let alone a flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("look at what has happened to flag{n0t_th3_fl4g_l0l} who have never flag{n0t_th3_fl4g_l0l} asked, \"smoking or non?\" is this what nature intended for us? to be forcibly addicted to smoke machines and man-made wooden slat work camps? \n"); sleep(1);
printf("living out our lives as flag{n0t_th3_fl4g_l0l} slaves to the white man? \n"); sleep(1);
printf("what are we gonna do? \n"); sleep(1);
printf("he's playing the species card. \n"); sleep(1);
printf("ladies and gentlemen, please, free these flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("free the flag{n0t_th3_fl4g_l0l} free the flag{n0t_th3_fl4g_l0l} free the flag{n0t_th3_fl4g_l0l} free the flag{n0t_th3_fl4g_l0l} free the flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("the court finds in favor of the flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} we won! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} knew you could do it! high-five! \n"); sleep(1);
printf("sorry. \n"); sleep(1);
printf("i'm ok! you know what this means? \n"); sleep(1);
printf("all the flag{n0t_th3_fl4g_l0l} will finally belong to the flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("now we won't have to work so hard all the time. \n"); sleep(1);
printf("this is an unholy perversion of the balance of nature, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("you'll regret this. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} how much flag{n0t_th3_fl4g_l0l} is out there? \n"); sleep(1);
printf("all right. one at a time. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} who are you wearing? \n"); sleep(1);
printf("my sweater is ralph lauren, and flag{n0t_th3_fl4g_l0l} have no pants. \n"); sleep(1);
printf("what if flag{n0t_th3_fl4g_l0l} right? \n"); sleep(1);
printf("what do you mean? \n"); sleep(1);
printf("we've flag{n0t_th3_fl4g_l0l} living the flag{n0t_th3_fl4g_l0l} way a long time, 27 million years. \n"); sleep(1);
printf("congratulations on your victory. what will you demand as a settlement? \n"); sleep(1);
printf("first, we'll demand a complete shutdown of all flag{n0t_th3_fl4g_l0l} work camps. \n"); sleep(1);
printf("then we want back the flag{n0t_th3_fl4g_l0l} that was ours to begin with, every last drop. \n"); sleep(1);
printf("we demand an end to the glorification of the bear as anything more than a filthy, smelly, bad-breath stink machine. \n"); sleep(1);
printf("we're all aware of what they do in the woods. \n"); sleep(1);
printf("wait for my signal. take him out. \n"); sleep(1);
printf("he'll have nauseous for a few hours, then he'll be fine. \n"); sleep(1);
printf("and we will no longer tolerate flag{n0t_th3_fl4g_l0l} nicknames... \n"); sleep(1);
printf("but it's just a prance-about stage name! \n"); sleep(1);
printf("...unnecessary inclusion of flag{n0t_th3_fl4g_l0l} in bogus health products and la-dee-da human tea-time snack garnishments. \n"); sleep(1);
printf("can't breathe. \n"); sleep(1);
printf("bring it in, boys! \n"); sleep(1);
printf("hold it right there! good. \n"); sleep(1);
printf("tap it. \n"); sleep(1);
printf("mr. buzzwell, we just passed three cups and there's gallons more coming! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} think we need to shut down! \n"); sleep(1);
printf("shut down? we've never shut down. \n"); sleep(1);
printf("shut down flag{n0t_th3_fl4g_l0l} production! \n"); sleep(1);
printf("stop making flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("turn your key, sir! \n"); sleep(1);
printf("what do we do now? \n"); sleep(1);
printf("cannonball! \n"); sleep(1);
printf("we're shutting flag{n0t_th3_fl4g_l0l} production! \n"); sleep(1);
printf("mission abort. \n"); sleep(1);
printf("aborting pollination and nectar detail. \n"); sleep(1);
printf("returning to base. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} you wouldn't believe how much flag{n0t_th3_fl4g_l0l} was out there. \n"); sleep(1);
printf("oh, yeah? \n"); sleep(1);
printf("what's going on? where is everybody? \n"); sleep(1);
printf("are they out celebrating? \n"); sleep(1);
printf("they're home. \n"); sleep(1);
printf("they don't know what to do. laying out, sleeping in. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} heard your uncle carl was on his way to san antonio with a cricket. \n"); sleep(1);
printf("at least we got our flag{n0t_th3_fl4g_l0l} back. \n"); sleep(1);
printf("sometimes flag{n0t_th3_fl4g_l0l} think, so what if humans liked our flag{n0t_th3_fl4g_l0l} who wouldn't? \n"); sleep(1);
printf("it's the greatest thing in the world! flag{n0t_th3_fl4g_l0l} was excited to be part of making it. \n"); sleep(1);
printf("this was my new desk. this was my new job. flag{n0t_th3_fl4g_l0l} wanted to do it really well. and now... \n"); sleep(1);
printf("now flag{n0t_th3_fl4g_l0l} can't. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't understand why they're not happy. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} thought their lives would be better! \n"); sleep(1);
printf("they're doing nothing. it's amazing. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} really changes people. \n"); sleep(1);
printf("you don't have any idea what's going on, do you? \n"); sleep(1);
printf("what did you want to show me? \n"); sleep(1);
printf("this. \n"); sleep(1);
printf("what happened here? \n"); sleep(1);
printf("that is not the half of it. \n"); sleep(1);
printf("oh, no. oh, my. \n"); sleep(1);
printf("they're all wilting. \n"); sleep(1);
printf("doesn't look very good, does it? \n"); sleep(1);
printf("no. \n"); sleep(1);
printf("and whose fault do you think that is? \n"); sleep(1);
printf("you know, i'm gonna guess flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("specifically, me. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} didn't think flag{n0t_th3_fl4g_l0l} not needing to make flag{n0t_th3_fl4g_l0l} would affect all these things. \n"); sleep(1);
printf("it's not just flowers. fruits, vegetables, they all need flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("that's our whole sat test right there. \n"); sleep(1);
printf("take away produce, that affects the entire animal kingdom. \n"); sleep(1);
printf("and then, of course... \n"); sleep(1);
printf("the human species? \n"); sleep(1);
printf("so if there's no more pollination, it could all just go south here, couldn't it? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know this is also partly my fault. \n"); sleep(1);
printf("how about a suicide pact? \n"); sleep(1);
printf("how do we do it? \n"); sleep(1);
printf("i'll sting you, you step on me. \n"); sleep(1);
printf("that just kills you twice. \n"); sleep(1);
printf("right, right. \n"); sleep(1);
printf("listen, flag{n0t_th3_fl4g_l0l} sorry, but flag{n0t_th3_fl4g_l0l} gotta get going. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} had to open my mouth and talk. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} why are you leaving? \n"); sleep(1);
printf("where are you going? \n"); sleep(1);
printf("to the final tournament of roses parade in pasadena. \n"); sleep(1);
printf("they've moved it to this weekend because all the flowers are dying. \n"); sleep(1);
printf("it's the last chance i'll ever have to see it. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} just wanna say i'm sorry. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} never meant it to turn out like this. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know. me neither. \n"); sleep(1);
printf("tournament of roses. \n"); sleep(1);
printf("roses can't do sports. \n"); sleep(1);
printf("wait a minute. roses. roses? \n"); sleep(1);
printf("roses! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("roses?! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("roses are flowers! \n"); sleep(1);
printf("yes, they are. \n"); sleep(1);
printf("flowers, flag{n0t_th3_fl4g_l0l} pollen! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know. \n"); sleep(1);
printf("that's why this is the last parade. \n"); sleep(1);
printf("maybe not. \n"); sleep(1);
printf("could you ask him to slow down? \n"); sleep(1);
printf("could you slow down? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("ok, flag{n0t_th3_fl4g_l0l} made a huge mistake. \n"); sleep(1);
printf("this is a total disaster, all my fault. \n"); sleep(1);
printf("yes, it kind of is. \n"); sleep(1);
printf("i've ruined the planet. flag{n0t_th3_fl4g_l0l} wanted to help you with the flower shop. i've made it worse. \n"); sleep(1);
printf("actually, it's completely closed down. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} thought maybe you were remodeling. \n"); sleep(1);
printf("but flag{n0t_th3_fl4g_l0l} have another idea, and it's greater than my previous ideas combined. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't want to hear it! \n"); sleep(1);
printf("all right, they have the roses, the roses have the pollen. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know every flag{n0t_th3_fl4g_l0l} plant and flower bud in this park. \n"); sleep(1);
printf("all we gotta do is get what they've got back here with what we've got. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("park. \n"); sleep(1);
printf("pollen! \n"); sleep(1);
printf("flowers. \n"); sleep(1);
printf("repollination! \n"); sleep(1);
printf("across the nation! \n"); sleep(1);
printf("tournament of roses, pasadena, california. \n"); sleep(1);
printf("they've got nothing but flowers, floats and cotton candy. \n"); sleep(1);
printf("security will be tight. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} have an idea. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} bloome, ftd. \n"); sleep(1);
printf("official floral business. it's real. \n"); sleep(1);
printf("sorry, ma'am. nice brooch. \n"); sleep(1);
printf("thank you. it was a gift. \n"); sleep(1);
printf("once inside, we just pick the right float. \n"); sleep(1);
printf("how about the princess and the pea? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} could be the princess, and you could be the pea! \n"); sleep(1);
printf("yes, flag{n0t_th3_fl4g_l0l} got it. \n"); sleep(1);
printf("where should flag{n0t_th3_fl4g_l0l} sit? \n"); sleep(1);
printf("what are you? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} believe i'm the pea. \n"); sleep(1);
printf("the pea? \n"); sleep(1);
printf("it goes under the mattresses. \n"); sleep(1);
printf("not in this fairy tale, sweetheart. \n"); sleep(1);
printf("i'm getting the marshal. \n"); sleep(1);
printf("you do that! this whole parade is a fiasco! \n"); sleep(1);
printf("let's see what this baby'll do. \n"); sleep(1);
printf("hey, what are you doing?! \n"); sleep(1);
printf("then all we do is blend in with traffic... without arousing suspicion. \n"); sleep(1);
printf("once at the airport, there's no stopping us. \n"); sleep(1);
printf("stop! security. \n"); sleep(1);
printf("you and your insect pack your float? \n"); sleep(1);
printf("yes. \n"); sleep(1);
printf("has it flag{n0t_th3_fl4g_l0l} in your possession the entire time? \n"); sleep(1);
printf("would you remove your shoes? \n"); sleep(1);
printf("remove your stinger. \n"); sleep(1);
printf("it's part of me. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} know. just having some fun. \n"); sleep(1);
printf("enjoy your flight. \n"); sleep(1);
printf("then if we're lucky, we'll have just enough pollen to do the job. \n"); sleep(1);
printf("can you believe how lucky we are? we have just enough pollen to do the job! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} think this is gonna work. \n"); sleep(1);
printf("it's got to work. \n"); sleep(1);
printf("attention, passengers, this is captain scott. we have a bit of bad weather in new york. it looks like we'll experience a couple hours delay. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} these are cut flowers with no water. they'll never make it. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} gotta get up there and talk to them. \n"); sleep(1);
printf("be careful. \n"); sleep(1);
printf("can flag{n0t_th3_fl4g_l0l} get help with the sky mall magazine? i'd like to order the talking inflatable nose and ear hair trimmer. \n"); sleep(1);
printf("captain, i'm in a real situation. \n"); sleep(1);
printf("what'd you say, hal? \n"); sleep(1);
printf("nothing. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("don't freak out! my entire species... \n"); sleep(1);
printf("what are you doing? \n"); sleep(1);
printf("wait a minute! i'm an attorney! \n"); sleep(1);
printf("who's an attorney? \n"); sleep(1);
printf("don't move. \n"); sleep(1);
printf("oh, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("good afternoon, passengers. this is your captain. would a miss flag{n0t_th3_fl4g_l0l} bloome in 24b please report to the cockpit? and please hurry! \n"); sleep(1);
printf("what happened here? \n"); sleep(1);
printf("there was a dustbuster, a toupee, a life raft exploded. \n"); sleep(1);
printf("one's bald, one's in a boat, they're both unconscious! \n"); sleep(1);
printf("is that another flag{n0t_th3_fl4g_l0l} joke? \n"); sleep(1);
printf("no! \n"); sleep(1);
printf("no one's flag{n0t_th3_fl4g_l0l} the plane! \n"); sleep(1);
printf("this is jfk control tower, flight 356. what's your status? \n"); sleep(1);
printf("this is flag{n0t_th3_fl4g_l0l} bloome. i'm a florist from new york. \n"); sleep(1);
printf("where's the pilot? \n"); sleep(1);
printf("he's unconscious, and so is the copilot. \n"); sleep(1);
printf("not good. does anyone onboard have flight experience? \n"); sleep(1);
printf("as a matter of fact, there is. \n"); sleep(1);
printf("who's that? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("from the flag{n0t_th3_fl4g_l0l} trial?! oh, great. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} this is nothing more than a big metal flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("it's got giant wings, huge engines. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't flag{n0t_th3_fl4g_l0l} a plane. \n"); sleep(1);
printf("why not? isn't john travolta a pilot? \n"); sleep(1);
printf("yes. \n"); sleep(1);
printf("how hard could it be? \n"); sleep(1);
printf("wait, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("we're headed into some lightning. \n"); sleep(1);
printf("this is bob bumble. we have some late-breaking news from jfk airport, where a suspenseful scene is developing. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} fresh from his legal victory... \n"); sleep(1);
printf("that's flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("...is attempting to land a plane, loaded with people, flowers and an incapacitated flight crew. \n"); sleep(1);
printf("flowers?! \n"); sleep(1);
printf("we have a storm in the area and two individuals at the controls with absolutely no flight experience. \n"); sleep(1);
printf("just a minute. there's a flag{n0t_th3_fl4g_l0l} on that plane. \n"); sleep(1);
printf("i'm quite familiar with mr. flag{n0t_th3_fl4g_l0l} and his no-account compadres. \n"); sleep(1);
printf("they've done enough damage. \n"); sleep(1);
printf("but isn't he your only hope? \n"); sleep(1);
printf("technically, a flag{n0t_th3_fl4g_l0l} shouldn't be able to flag{n0t_th3_fl4g_l0l} at all. \n"); sleep(1);
printf("their wings are too small... haven't we heard this a million times? \n"); sleep(1);
printf("\"the surface area of the wings and body mass make no sense.\" \n"); sleep(1);
printf("get this on the air! \n"); sleep(1);
printf("got it. \n"); sleep(1);
printf("stand by. \n"); sleep(1);
printf("we're going live. \n"); sleep(1);
printf("the way we work may be a mystery to you. making flag{n0t_th3_fl4g_l0l} takes a lot of flag{n0t_th3_fl4g_l0l} doing a lot of small jobs. \n"); sleep(1);
printf("but let me tell you about a small job. if you do it well, it makes a big difference. \n"); sleep(1);
printf("more than we realized. to us, to everyone. \n"); sleep(1);
printf("that's why flag{n0t_th3_fl4g_l0l} want to get flag{n0t_th3_fl4g_l0l} back to working together. that's the flag{n0t_th3_fl4g_l0l} way! we're not made of jell-o. \n"); sleep(1);
printf("we get behind a fellow. \n"); sleep(1);
printf("black and yellow! \n"); sleep(1);
printf("hello! \n"); sleep(1);
printf("left, right, down, hover. \n"); sleep(1);
printf("hover? \n"); sleep(1);
printf("forget hover. \n"); sleep(1);
printf("this isn't so hard. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} what happened?! \n"); sleep(1);
printf("wait, flag{n0t_th3_fl4g_l0l} think we were on autopilot the whole time. \n"); sleep(1);
printf("that may have flag{n0t_th3_fl4g_l0l} helping me. \n"); sleep(1);
printf("and now we're not! \n"); sleep(1);
printf("so it turns out flag{n0t_th3_fl4g_l0l} cannot flag{n0t_th3_fl4g_l0l} a plane. \n"); sleep(1);
printf("all of you, let's get behind this fellow! move it out! \n"); sleep(1);
printf("move out! \n"); sleep(1);
printf("our only chance is if flag{n0t_th3_fl4g_l0l} do what i'd do, you copy me with the wings of the plane! \n"); sleep(1);
printf("don't have to yell. \n"); sleep(1);
printf("i'm not yelling! we're in a lot of trouble. \n"); sleep(1);
printf("it's very hard to concentrate with that panicky tone in your voice! \n"); sleep(1);
printf("it's not a tone. i'm panicking! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} can't do this! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} pull yourself together. you have to snap out of it! \n"); sleep(1);
printf("you snap out of it. \n"); sleep(1);
printf("you snap out of it. \n"); sleep(1);
printf("you snap out of it! \n"); sleep(1);
printf("you snap out of it! \n"); sleep(1);
printf("you snap out of it! \n"); sleep(1);
printf("you snap out of it! \n"); sleep(1);
printf("you snap out of it! \n"); sleep(1);
printf("you snap out of it! \n"); sleep(1);
printf("hold it! \n"); sleep(1);
printf("why? come on, it's my turn. \n"); sleep(1);
printf("how is the plane flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know. \n"); sleep(1);
printf("hello? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} got any flowers for a happy occasion in there? \n"); sleep(1);
printf("the pollen jocks! \n"); sleep(1);
printf("they do get behind a fellow. \n"); sleep(1);
printf("black and yellow. \n"); sleep(1);
printf("hello. \n"); sleep(1);
printf("all right, let's drop this tin can on the blacktop. \n"); sleep(1);
printf("where? flag{n0t_th3_fl4g_l0l} can't see anything. can you? \n"); sleep(1);
printf("no, nothing. it's all cloudy. \n"); sleep(1);
printf("come on. you got to think flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("wait a minute. flag{n0t_th3_fl4g_l0l} think i'm feeling something. \n"); sleep(1);
printf("what? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} don't know. it's strong, pulling me. \n"); sleep(1);
printf("like a 27-million-year-old instinct. \n"); sleep(1);
printf("bring the nose down. \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("what in the world is on the tarmac? \n"); sleep(1);
printf("get some lights on that! \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} aim for the flower. \n"); sleep(1);
printf("ok. \n"); sleep(1);
printf("cut the engines. we're going in on flag{n0t_th3_fl4g_l0l} power. ready, boys? \n"); sleep(1);
printf("affirmative! \n"); sleep(1);
printf("good. good. easy, now. that's it. \n"); sleep(1);
printf("land on that flower! \n"); sleep(1);
printf("ready? full reverse! \n"); sleep(1);
printf("spin it around! \n"); sleep(1);
printf("not that flower! the other one! \n"); sleep(1);
printf("which one? \n"); sleep(1);
printf("that flower. \n"); sleep(1);
printf("i'm aiming at the flower! \n"); sleep(1);
printf("that's a fat guy in a flowered shirt. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} mean the giant pulsating flower made of millions of flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("pull forward. nose down. tail up. \n"); sleep(1);
printf("rotate around it. \n"); sleep(1);
printf("this is insane, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("this's the only way flag{n0t_th3_fl4g_l0l} know how to flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("am flag{n0t_th3_fl4g_l0l} koo-koo-kachoo, or is this plane flag{n0t_th3_fl4g_l0l} in an insect-like pattern? \n"); sleep(1);
printf("get your nose in there. don't be afraid. smell it. full reverse! \n"); sleep(1);
printf("just drop it. be a part of it. \n"); sleep(1);
printf("aim for the center! \n"); sleep(1);
printf("now drop it in! drop it in, woman! \n"); sleep(1);
printf("come on, already. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} we did it! you taught me how to flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("yes. no high-five! \n"); sleep(1);
printf("right. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} it worked! \n"); sleep(1);
printf("did you see the giant flower? \n"); sleep(1);
printf("what giant flower? where? of course \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} saw the flower! that was genius! \n"); sleep(1);
printf("thank you. \n"); sleep(1);
printf("but we're not done yet. \n"); sleep(1);
printf("listen, everyone! \n"); sleep(1);
printf("this runway is covered with the last pollen from the last flowers available anywhere on earth. \n"); sleep(1);
printf("that means this is our last chance. we're the only ones who make flag{n0t_th3_fl4g_l0l} pollinate flowers and dress like this. \n"); sleep(1);
printf("if we're gonna survive as a species, this is our moment! what do you say? \n"); sleep(1);
printf("are we going to be flag{n0t_th3_fl4g_l0l} or just museum of natural history keychains? \n"); sleep(1);
printf("we're flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("keychain! \n"); sleep(1);
printf("then follow me! except keychain. \n"); sleep(1);
printf("hold on, flag{n0t_th3_fl4g_l0l} here. you've earned this. \n"); sleep(1);
printf("yeah! \n"); sleep(1);
printf("i'm a pollen jock! and it's a perfect fit. all flag{n0t_th3_fl4g_l0l} gotta do are the sleeves. \n"); sleep(1);
printf("oh, yeah. \n"); sleep(1);
printf("that's our flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("mom! the flag{n0t_th3_fl4g_l0l} are back! \n"); sleep(1);
printf("if anybody needs to make a call, now's the time. flag{n0t_th3_fl4g_l0l} got a feeling we'll be working late tonight! \n"); sleep(1);
printf("here's your change. have a great afternoon! can flag{n0t_th3_fl4g_l0l} help who's next? \n"); sleep(1);
printf("would you like some flag{n0t_th3_fl4g_l0l} with that? \n"); sleep(1);
printf("it is flag{n0t_th3_fl4g_l0l} don't forget these. \n"); sleep(1);
printf("milk, cream, cheese, it's all me. and flag{n0t_th3_fl4g_l0l} don't see a nickel! \n"); sleep(1);
printf("sometimes flag{n0t_th3_fl4g_l0l} just feel like a piece of meat! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} had no idea. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} i'm sorry. \n"); sleep(1);
printf("have you got a moment? \n"); sleep(1);
printf("would you excuse me? \n"); sleep(1);
printf("my mosquito associate will help you. \n"); sleep(1);
printf("sorry i'm late. \n"); sleep(1);
printf("he's a lawyer too? \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} was already a blood-sucking parasite. all flag{n0t_th3_fl4g_l0l} needed was a briefcase. \n"); sleep(1);
printf("have a great afternoon! \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} flag{n0t_th3_fl4g_l0l} just got this huge tulip order, and flag{n0t_th3_fl4g_l0l} can't get them anywhere. \n"); sleep(1);
printf("no problem, vannie. just leave it to me. \n"); sleep(1);
printf("you're a lifesaver, flag{n0t_th3_fl4g_l0l} can flag{n0t_th3_fl4g_l0l} help who's next? \n"); sleep(1);
printf("all right, scramble, jocks! it's time to flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("thank you, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("that flag{n0t_th3_fl4g_l0l} is living my life! \n"); sleep(1);
printf("let it go, flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("when will this nightmare end?! \n"); sleep(1);
printf("let it all go. \n"); sleep(1);
printf("beautiful day to flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("sure is. \n"); sleep(1);
printf("between you and me, \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} was dying to get out of that office. \n"); sleep(1);
printf("you have got to start thinking flag{n0t_th3_fl4g_l0l} my friend. \n"); sleep(1);
printf("thinking flag{n0t_th3_fl4g_l0l} \n"); sleep(1);
printf("me? \n"); sleep(1);
printf("hold it. let's just stop for a second. hold it. \n"); sleep(1);
printf("i'm sorry. i'm sorry, everyone. can we stop here? \n"); sleep(1);
printf("i'm not making a major life decision during a production number! \n"); sleep(1);
printf("all right. take ten, everybody. wrap it up, guys. \n"); sleep(1);
printf("flag{n0t_th3_fl4g_l0l} had virtually no rehearsal for that. \n"); sleep(1);
}
